default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: frank_engine_development

test:
  <<: *default
  database:  frank_engine_test

production:
  <<: *default
  adapter: postgresql
